# params/control.yaml
# Common parameters for control
---

# Dynamic parameters cannot have a namespace
base_speed:      0.4
lateral_gain:     13.93 #5
reference_lane_x: 80.1
pedestrian_width_min: 55
